[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
kuchiki = "0.8.1"
serde = { version = "1.0.217", features = ["derive"] }
actix-cors = "0.7.0"
log = "0.4.25"
env_logger = "0.11.6"